services:
  - type: web
    name: website-kelas-x-tkj-bk
    env: docker
    plan: starter
    disk:
      name: kelas-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /data/database.db
      - key: UPLOAD_PATH
        value: /data/uploads
      - key: BACKUP_PATH
        value: /data/backups
