const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const COOKIE = 'class_access_token';
const roles = ['developer', 'wali_kelas', 'murid'];
const json = (res, status, body) => res.status(status).json(body);
const fail = (res, status, message) => json(res, status, { success: false, message });
const token = (req) => (req.headers.cookie || '').split(';').map((v) => v.trim()).find((v) => v.startsWith(`${COOKIE}=`))?.slice(COOKIE.length + 1);
const headers = (access, extra = {}) => ({ apikey: SERVICE_KEY, Authorization: `Bearer ${access || SERVICE_KEY}`, ...extra });
async function request(path, options = {}, access) {
  if (!SUPABASE_URL || !SERVICE_KEY) throw new Error('Supabase belum dikonfigurasi');
  const response = await fetch(`${SUPABASE_URL}${path}`, { ...options, headers: headers(access, options.headers) });
  const data = response.status === 204 ? null : await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(data.message || data.error || 'Permintaan database gagal'), { status: response.status });
  return data;
}
const rest = (table, query = '') => `/rest/v1/${table}${query}`;
async function current(req) {
  const access = token(req); if (!access) return null;
  const auth = await request('/auth/v1/user', {}, access).catch(() => null); if (!auth) return null;
  const rows = await request(rest(`users?id=eq.${auth.id}&select=id,username,nama,role`), {}, access).catch(() => []);
  return rows[0] ? { ...rows[0], access } : null;
}
function requireUser(req, res, allowed) { return current(req).then((user) => { if (!user) { fail(res, 401, 'Silakan login terlebih dahulu'); return null; } if (allowed && !allowed.includes(user.role)) { fail(res, 403, 'Anda tidak memiliki akses'); return null; } return user; }); }
function publicUrl(path) { return `${SUPABASE_URL}/storage/v1/object/public/class-media/${path}`; }
async function upload(req, field, prefix, maxBytes, user) {
  const file = req.body?.[field];
  if (!file || !file.data || !['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > maxBytes) throw new Error('File harus berupa JPG, PNG, atau WebP dengan ukuran yang sesuai');
  const ext = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' }[file.type];
  const path = `${prefix}/${user.id}/${crypto.randomUUID()}.${ext}`;
  await request(`/storage/v1/object/class-media/${path}`, { method: 'POST', headers: { 'Content-Type': file.type }, body: Buffer.from(file.data, 'base64') }, user.access);
  return publicUrl(path);
}
module.exports = async (req, res) => {
  try {
    const route = (req.query.route || []).join('/').replace(/^developer\/members/, 'admin/members');
    if (route === 'login' && req.method === 'POST') {
      const { username = '', password = '', role } = req.body || {}; const normalized = role === 'wali' ? 'wali_kelas' : role === 'siswa' ? 'murid' : role;
      if (!username || !password || !roles.includes(normalized)) return fail(res, 400, 'Username, password, dan role wajib diisi');
      const login = await request('/auth/v1/token?grant_type=password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: `${String(username).trim().toLowerCase()}@members.local`, password }) });
      const users = await request(rest(`users?id=eq.${login.user.id}&select=id,username,nama,role`)); const user = users[0];
      if (!user || user.role !== normalized) return fail(res, 401, 'Username, password, atau role tidak sesuai');
      res.setHeader('Set-Cookie', `${COOKIE}=${login.access_token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${login.expires_in}`); return json(res, 200, { success: true, message: 'Login berhasil', user });
    }
    if (route === 'logout' && req.method === 'POST') { res.setHeader('Set-Cookie', `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`); return json(res, 200, { success: true, message: 'Logout berhasil' }); }
    if (route === 'me' && req.method === 'GET') { const user = await current(req); return json(res, 200, { success: true, loggedIn: !!user, user: user && (({ id, username, nama, role }) => ({ id, username, nama, role }))(user) }); }
    if (route === 'member-registration-status' && req.method === 'GET') { const range = await request(rest(`users?role=eq.murid&select=id`, ''), { headers: { Prefer: 'count=exact', Range: '0-0' } }); const count = Number(range.length || 0); return json(res, 200, { success: true, count, max: 30, remaining: Math.max(0, 30 - count), available: count < 30 }); }
    if (route === 'member-register' && req.method === 'POST') {
      const { nama = '', username = '', password = '', kelas = '', bio = '' } = req.body || {}; if (!nama.trim() || !kelas.trim() || password.length < 6) return fail(res, 400, 'Nama, username, kelas, dan password minimal 6 karakter wajib diisi');
      const count = await request(rest('users?role=eq.murid&select=id')); if (count.length >= 30) return fail(res, 403, 'Kuota 30 anggota sudah penuh');
      const email = `${username.trim().toLowerCase()}@members.local`; const created = await request('/auth/v1/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, email_confirm: true }) });
      try { await request(rest('users'), { method: 'POST', headers: { 'Content-Type': 'application/json', Prefer: 'return=representation' }, body: JSON.stringify({ id: created.id, username: username.trim().toLowerCase(), nama: nama.trim(), role: 'murid' }) }); await request(rest('member_profiles'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ user_id: created.id, nama_lengkap: nama.trim(), kelas: kelas.trim(), bio: String(bio).trim() }) }); } catch (error) { await request(`/auth/v1/admin/users/${created.id}`, { method: 'DELETE' }).catch(() => {}); throw error; }
      return json(res, 201, { success: true, message: 'Pendaftaran anggota berhasil' });
    }
    if (route === 'members' && req.method === 'GET') { const members = await request(rest('users?select=id,account_name:nama,role,member_profiles(nama_lengkap,kelas,jabatan,bio,photo_url)&order=nama')); return json(res, 200, { success: true, members: members.map(({ member_profiles, ...m }) => ({ ...m, ...(member_profiles || {}) })) }); }
    if (route === 'announcements' && req.method === 'GET') return json(res, 200, { success: true, announcements: await request(rest('announcements?select=id,title,content,image_url,expires_at,created_at&order=created_at.desc')) });
    if (route === 'class-content' && req.method === 'GET') { const [info, schedule] = await Promise.all([request(rest('class_info?id=eq.1&select=title,content')), request(rest('class_schedule?select=day,subjects&order=day'))]); return json(res, 200, { success: true, info: info[0] || null, schedule }); }
    if (route === 'class-structure' && req.method === 'GET') { const structure = await request(rest('class_structure?select=position,user_id,users(nama,member_profiles(nama_lengkap,kelas,jabatan,photo_url))')); return json(res, 200, { success: true, structure: structure.map(({ users, ...s }) => ({ ...s, nama: users?.member_profiles?.nama_lengkap || users?.nama || null, kelas: users?.member_profiles?.kelas || null, jabatan: users?.member_profiles?.jabatan || null, photo_url: users?.member_profiles?.photo_url || null })) }); }
    if (route === 'gallery' && req.method === 'GET') { const photos = await request(rest('class_gallery?select=id,title,description,photo_url,created_at,users(nama)&order=created_at.desc')); const user = await current(req); return json(res, 200, { success: true, photos: photos.map(({ users, ...p }) => ({ ...p, uploaded_by_name: users?.nama })), canManage: ['developer', 'wali_kelas'].includes(user?.role) }); }
    const user = await requireUser(req, res); if (!user) return;
    if (route === 'dashboard' && req.method === 'GET') return json(res, 200, { success: true, user: (({ id, username, nama, role }) => ({ id, username, nama, role }))(user), permissions: { developer: ['kelola pengguna', 'kelola pengumuman', 'lihat data kelas'], wali_kelas: ['kelola pengumuman', 'lihat data murid', 'lihat jadwal kelas'], murid: ['lihat pengumuman', 'lihat jadwal kelas', 'lihat profil'] }[user.role] });
    if (route === 'profile' && req.method === 'GET') { const profile = await request(rest(`member_profiles?user_id=eq.${user.id}&select=nama_lengkap,kelas,jabatan,bio,photo_url,updated_at`), {}, user.access); return json(res, 200, { success: true, profile: profile[0] || null }); }
    if (route === 'profile' && req.method === 'PUT') { const { nama_lengkap, kelas, jabatan = '', bio = '' } = req.body || {}; if (!nama_lengkap?.trim() || !kelas?.trim() || jabatan.length > 80) return fail(res, 400, 'Nama dan kelas wajib diisi'); await request(rest(`member_profiles?user_id=eq.${user.id}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nama_lengkap: nama_lengkap.trim(), kelas: kelas.trim(), jabatan: jabatan.trim(), bio: bio.trim() }) }, user.access); await request(rest(`users?id=eq.${user.id}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nama: nama_lengkap.trim() }) }); return json(res, 200, { success: true, message: 'Profil berhasil disimpan' }); }
    if (route === 'profile/photo' && req.method === 'POST') { const photo_url = await upload(req, 'foto', 'profiles', 5 * 1024 * 1024, user); await request(rest(`member_profiles?user_id=eq.${user.id}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ photo_url }) }, user.access); return json(res, 200, { success: true, message: 'Foto profil berhasil disimpan', photo_url }); }
    if (!['developer', 'wali_kelas'].includes(user.role)) return fail(res, 403, 'Anda tidak memiliki akses');
    if (route === 'announcements' && req.method === 'POST') { const { title = '', content = '', duration } = req.body || {}; if (!title.trim() || !content.trim()) return fail(res, 400, 'Judul dan isi pengumuman wajib diisi'); const image_url = req.body?.poster ? await upload(req, 'poster', 'announcements', 8 * 1024 * 1024, user) : null; const expires_at = duration === 'permanent' ? null : new Date(Date.now() + Number(duration) * 86400000).toISOString(); await request(rest('announcements'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: title.trim(), content: content.trim(), image_url, expires_at }) }, user.access); return json(res, 201, { success: true, message: 'Pengumuman berhasil ditambahkan' }); }
    if (route === 'gallery' && req.method === 'POST') { const { title = '', description = '' } = req.body || {}; if (!title.trim()) return fail(res, 400, 'Judul foto wajib diisi'); const photo_url = await upload(req, 'foto', 'gallery', 8 * 1024 * 1024, user); await request(rest('class_gallery'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: title.trim(), description: description.trim(), photo_url, uploaded_by: user.id }) }, user.access); return json(res, 201, { success: true, message: 'Foto berhasil ditambahkan' }); }
    if (route === 'class-content' && req.method === 'PUT') { const { title = '', content = '', schedule = [] } = req.body || {}; if (!title.trim() || !content.trim() || !Array.isArray(schedule) || schedule.length !== 6) return fail(res, 400, 'Info kelas dan jadwal wajib diisi'); await request(rest('class_info?id=eq.1'), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: title.trim(), content: content.trim() }) }, user.access); for (const item of schedule) await request(rest(`class_schedule?day=eq.${encodeURIComponent(item.day)}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ subjects: String(item.subjects || '').trim() }) }, user.access); return json(res, 200, { success: true, message: 'Info kelas dan jadwal berhasil diperbarui' }); }
    if (route === 'class-structure' && req.method === 'PUT') { const positions = ['wali_kelas', 'ketua', 'wakil', 'sekretaris']; const values = req.body || {}; const ids = positions.map((p) => values[p] || null); if (ids.slice(1).filter(Boolean).length !== new Set(ids.slice(1).filter(Boolean)).size) return fail(res, 400, 'Satu anggota tidak boleh memegang dua posisi'); for (const position of positions) await request(rest(`class_structure?position=eq.${position}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ user_id: values[position] || null }) }, user.access); return json(res, 200, { success: true, message: 'Struktur kelas berhasil disimpan' }); }
    if (route === 'admin/members' && req.method === 'GET') { const members = await request(rest('users?select=id,username,nama,role,member_profiles(nama_lengkap,kelas,jabatan,bio,photo_url)&order=nama'), {}, user.access); return json(res, 200, { success: true, members: members.map(({ member_profiles, ...m }) => ({ ...m, ...(member_profiles || {}) })) }); }
    const member = route.match(/^admin\/members\/([\w-]+)(?:\/(profile|profile\/photo|reset-password))?$/);
    if (member && req.method === 'PUT' && member[2] === 'profile') { const { nama_lengkap, kelas, jabatan = '', bio = '' } = req.body || {}; if (!nama_lengkap?.trim() || !kelas?.trim() || jabatan.length > 80) return fail(res, 400, 'Nama dan kelas wajib diisi'); await request(rest(`member_profiles?user_id=eq.${member[1]}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nama_lengkap: nama_lengkap.trim(), kelas: kelas.trim(), jabatan: jabatan.trim(), bio: bio.trim() }) }, user.access); return json(res, 200, { success: true, message: 'Profil anggota berhasil diperbarui' }); }
    if (member && req.method === 'POST' && member[2] === 'profile/photo') { const photo_url = await upload(req, 'foto', 'profiles', 5 * 1024 * 1024, user); await request(rest(`member_profiles?user_id=eq.${member[1]}`), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ photo_url }) }, user.access); return json(res, 200, { success: true, message: 'Foto profil anggota berhasil disimpan', photo_url }); }
    if (member && req.method === 'POST' && member[2] === 'reset-password') { if (user.role !== 'developer') return fail(res, 403, 'Anda tidak memiliki akses'); const password = req.body?.password || ''; if (password.length < 6) return fail(res, 400, 'Password baru minimal 6 karakter'); const target = await request(rest(`users?id=eq.${member[1]}&select=id,role`), {}, user.access); if (!target[0] || target[0].role !== 'murid') return fail(res, 404, 'Anggota tidak ditemukan'); await request(`/auth/v1/admin/users/${member[1]}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); return json(res, 200, { success: true, message: 'Password anggota berhasil diubah' }); }
    if (member && req.method === 'DELETE' && !member[2]) { if (user.role !== 'developer') return fail(res, 403, 'Anda tidak memiliki akses'); if (member[1] === user.id) return fail(res, 400, 'Akun yang sedang digunakan tidak dapat dihapus'); await request(`/auth/v1/admin/users/${member[1]}`, { method: 'DELETE' }); return json(res, 200, { success: true, message: 'Akun berhasil dihapus' }); }
    const announcement = route.match(/^announcements\/(\d+)$/); if (announcement && req.method === 'DELETE') { await request(rest(`announcements?id=eq.${announcement[1]}`), { method: 'DELETE' }, user.access); return json(res, 200, { success: true, message: 'Pengumuman berhasil dihapus' }); }
    const gallery = route.match(/^gallery\/(\d+)$/); if (gallery && req.method === 'DELETE') { await request(rest(`class_gallery?id=eq.${gallery[1]}`), { method: 'DELETE' }, user.access); return json(res, 200, { success: true, message: 'Foto berhasil dihapus' }); }
    return fail(res, 404, 'Route tidak ditemukan');
  } catch (error) { return fail(res, error.status === 401 ? 401 : error.status === 409 ? 409 : 500, error.status === 409 ? 'Username sudah digunakan' : error.message || 'Terjadi kesalahan pada server'); }
};
